# Generated by Django 4.1.3 on 2022-11-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='place',
            field=models.CharField(max_length=250),
        ),
    ]
