# Generated by Django 4.1.3 on 2022-12-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_alter_home_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.CharField(max_length=250),
        ),
    ]
